### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by Armin268** [pylbm/pylbm#175]
Hi.
I got:
ImportError: Building module wrapped_module_0 failed: ['distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat\n']

How can I fix this?

**Comment by gouarin** [comment]
You have to install a C compiler for Windows : https://visualstudio.microsoft.com

**Comment by Armin268** [comment]
I did it. But I got:
Error: command 'C:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2022\\\\BuildTools\\\\VC\\\\Tools\\\\MSVC\\\\14.36.32532\\\\bin\\\\HostX86\\\\x64\\\\cl.exe' failed with exit code 2\n"]

**Comment by Armin268** [comment]
the actual error:


raise CompileError(msg)

ImportError: Building module wrapped_module_0 failed: ["distutils.errors.CompileError: command 'C:\\\\Program Files\\\\Microsoft Visual Studio\\\\2022\\\\Community\\\\VC\\\\Tools\\\\MSVC\\\\14.36.32532\\\\bin\\\\HostX86\\\\x64\\\\cl.exe' failed with exit code 2\n"]

**Comment by gouarin** [comment]
I don't have enough information to understand why the compilation failed. With pylbm, you have several code generators. The one you try to use is Cython and to make it work, you have to compile a C code at the end. You can change this generator to numpy by adding an entry in the dictionary of the simulation `"generator": "numpy"`. It will work but it will be slower than with Cython.

How did you install pylbm? pip or conda? Since you have installed msvc, could you try to remove and reinstall cython?

**Comment by gouarin** [comment]
fixed in https://github.com/pylbm/pylbm/pull/180
