### ISSUE TITLE
square.tpl

### ISSUE THREAD

**Issue by quelusername** [pylbm/pylbm#92]
Hello, 
I'm trying to test the example "step.py" and many errors occured, but I solved them except one. 
I have the following error message : 

    raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: square.tpl

Do you have any suggestion ? 
Thanks

**Comment by gouarin** [comment]
@quelusername how did you install pylbm ?
If you used `pip`, it's normal that you have an issue.

I suggest using the master version of pylbm since we made a lot of improvements.

You can follow the installation steps written at the end of the readme file (https://github.com/pylbm/pylbm/blob/master/README.rst#from-source)

**Comment by quelusername** [comment]
I followed all the installation steps but an error still occurs : 

    raise CompileError(msg)
    ImportError: Building module wrapped_module_0 failed: ["distutils.errors.CompileError: command 'gcc' failed with exit status 1\n"]

I don't see at all where it comes from...

**Comment by gouarin** [comment]
Could you tell me which script you're trying?

Could you also add `'show_code': True` in the dictionary of the simulation and send me the output?

**Comment by quelusername** [comment]
I achieved to make it work, thanks for your help!

I saw in the description that you wanted to provide tools for multi-phase flows for example, are those already available?

**Comment by gouarin** [comment]
Good news.

We already have the possibility to construct a gradient of the conserved moments in order to compute the source term that you can have when you want to solve multi-phase flows. But we have no experience in that field and we have to test it. But the current version of pylbm should be able to solve these kinds of problems.

We hope to add some multi-phase flow examples in the next months.

**Comment by Armin268** [comment]
> @quelusername how did you install pylbm ? If you used `pip`, it's normal that you have an issue.
> 
> I suggest using the master version of pylbm since we made a lot of improvements.
> 
> You can follow the installation steps written at the end of the readme file (https://github.com/pylbm/pylbm/blob/master/README.rst#from-source)

sorry, may I know how did you solve the issue?

**Comment by daydayup1225** [comment]
@quelusername also meet the same problem? could you please tell how to solve this 'wrapped_module_0' problem?

**Comment by gouarin** [comment]
@daydayup1225 you need to use the source code of pylbm. This issue is fixed in https://github.com/pylbm/pylbm/pull/180.

I will update the version on pypi and conda-forge soon.
